# Nome do workflow
name: Deploy LeadHunterAI to GitHub Pages

# Define quando o workflow deve rodar
on:
  push:
    branches: ["main"] # Roda quando hÃ¡ um push na branch 'main'
  workflow_dispatch:

# PermissÃµes necessÃ¡rias para a publicaÃ§Ã£o no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Define os jobs (tarefas)
jobs:
  # Job para construir o projeto
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup Node.js ğŸŸ©
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn' # Cache para YARN, pois seu projeto o utiliza

      - name: Install Dependencies ğŸ“¦
        run: yarn install --frozen-lockfile # Comando para instalar dependÃªncias com Yarn

      - name: Build Project ğŸ—ï¸
        run: yarn build # Executa o script "build" do seu package.json

      - name: Setup Pages ğŸ› ï¸
        uses: actions/configure-pages@v5

      - name: Upload artifact ğŸ“¤
        uses: actions/upload-pages-artifact@v3
        with:
          # A pasta de saÃ­da do Vite Ã© a 'dist'
          path: './dist'

  # Job para publicar o projeto
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages ğŸš€
        id: deployment
        uses: actions/deploy-pages@v4
